name: afdian-sponsor
description: Generate afdian sponsors svg on github action
author: Sn0wo2

inputs:
  version:
    description: 'Release tag to fetch (e.g. v1.2.3). If empty, resolve from action ref or fallback to latest.'
    required: false
    default: ''
  cache:
    description: 'Enable cache for the binary. Default: enable'
    required: false
    default: 'enable'

runs:
  using: composite
  steps:
    - name: Install afdian-sponsor
      uses: jaxxstorm/action-install-gh-release@v1
      with:
        repo: Sn0wo2/afdian-sponsor
        tag: ${{ inputs.version || github.action_ref || 'latest' }}
        cache: ${{ inputs.cache == 'false' && '' || inputs.cache }}
    - name: Run afdian-sponsor
      shell: bash
      run: afdian-sponsor
