name: "afdian-sponsor"
description: "build afdian sponsor svg"
author: "Sn0wo2"

runs:
  using: "docker"
  image: "docker://ghcr.io/sn0wo2/afdian-sponsor:latest"
  env:
    AFDIAN_OUTPUT: "/github/workspace/afdian-sponsor.svg"
