name: afdian-sponsor
description: Generate afdian sponsors svg on github action
author: Sn0wo2

inputs:
  version:
    description: 'Release tag to fetch (e.g. v1.2.3). If empty, resolve from action ref or fallback to latest.'
    required: false
    default: ''
  cache:
    description: 'Enable cache for the binary. Default: enable'
    required: false
    default: 'enable'

runs:
  using: composite
  steps:
    - name: Resolve version
      id: resolve
      shell: bash
      run: |
        if [ -n "${{ inputs.version }}" ]; then
          echo "version=${{ inputs.version }}" >> "$GITHUB_OUTPUT"
        elif [[ "${{ github.action_ref }}" =~ ^v[0-9]+$ ]]; then
          latest=$(gh api repos/Sn0wo2/afdian-sponsor/releases \
            --jq '.[] | select(.tag_name | startswith("${{ github.action_ref }}.")) | .tag_name' | head -n1)
          echo "version=${latest:-latest}" >> "$GITHUB_OUTPUT"
        else
          echo "version=latest" >> "$GITHUB_OUTPUT"
        fi

    - name: Install afdian-sponsor
      uses: jaxxstorm/action-install-gh-release@v1
      with:
        repo: Sn0wo2/afdian-sponsor
        tag: ${{ steps.resolve.outputs.version }}
        cache: ${{ inputs.cache == 'false' && '' || inputs.cache }}

    - name: Run afdian-sponsor
      shell: bash
      run: afdian-sponsor
